version: '3'
services:
  web:
    build: site
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default

  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./www/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Adjusted path to nginx.conf
      - ./www:/var/www/html
    depends_on:
      - web
    networks:
      - default

networks:
  default:
    external:
      name: challenge-3iwj_default