/:
  Controller: "Security"
  Action: "register"

/register:
  Controller: "Security"
  Action: "register"

/login:
  Controller: "Security"
  Action: "login"

/logout:
  Controller: "Security"
  Action: "logout"

/dashboard:
  Controller: "Main"
  Action: "dashboard"
  Security: true
  Role: ["admin", "author"]

/confirm-email:
  Controller: "Security"
  Action: "confirmAccount"

/request-activate-account:
  Controller: "Security"
  Action: "requestActivateAccount"

/activate-account:
  Controller: "Security"
  Action: "activateAccount"

/request-password-reset:
  Controller: "Security"
  Action: "requestPasswordReset"

/reset-password:
  Controller: "Security"
  Action: "resetPassword"

/create-page:
  Controller: "PageController"
  Action: "create"

/store-page:
  Controller: "PageController"
  Action: "store"

/view-page/{slug}:
  Controller: "PageController"
  Action: "view"

/list-page:
  Controller: "PageController"
  Action: "list"

/edit-page:
  Controller: "PageController"
  Action: "edit"
  Method: "GET"
  Role: ["admin", "editor"]

/delete-page:
  Controller: "PageController"
  Action: "delete"
  Role: ["admin", "editor"]

/create-article:
  Controller: "ArticleController"
  Action: "create"

/store-article:
  Controller: "ArticleController"
  Action: "store"

/list-articles:
  Controller: "ArticleController"
  Action: "list"

/view-article:
  Controller: "ArticleController"
  Action: "view"

/add-comment:
  Controller: "ArticleController"
  Action: "addComment"

/store-comment:
  Controller: "CommentaireController"
  Action: "store"

/profil-user:
  Controller: "UserController"
  Action: "profil"

/edit-user:
  Controller: "UserController"
  Action: "edit"

/delete-user:
  Controller: "UserController"
  Action: "delete"
  Role: ["admin"]

/update-profil:
  Controller: "UserController"
  Action: "update"

/update:
  Controller: "UserController"
  Action: "update"
  Method: "POST"

/list-users:
  Controller: "UserController"
  Action: "list"

/edit-as-admin:
  Controller: "UserController"
  Action: "editAsAdmin"

/update-user:
  Controller: "UserController"
  Action: "updateUser"

/update-users-inline:
  Controller: "UserController"
  Action: "updateUsersInline"
  Method: "POST"
  Role: ["admin"]

/add-user:
  Controller: "UserController"
  Action: "add"
  Method: "GET,POST"
  Role: ["admin"]

/media:
  Controller: "MediaController"
  Action: "index"

/media/upload:
  Controller: "MediaController"
  Action: "upload"
  Method: "GET,POST"

/media/delete:
  Controller: "MediaController"
  Action: "delete"
  Method: "GET,POST"
  Role: ["admin", "editor"]

/report-comment:
  Controller: "CommentaireController"
  Action: "report"
  Method: "POST"

/delete-comment:
  Controller: "CommentaireController"
  Action: "delete"
  Method: "POST"
  Role: ["admin", "editor"]

/edit-article:
  Controller: "ArticleController"
  Action: "edit"
  Method: "GET"
  Role: ["admin", "editor"]

/update-article:
  Controller: "ArticleController"
  Action: "update"
  Method: "POST"
  Role: ["admin", "editor"]

/delete-article:
  Controller: "ArticleController"
  Action: "delete"
  Role: ["admin", "editor"]

/customize:
  Controller: "Main"
  Action: "customize"

/update-config:
  Controller: "CustomizeController"
  Action: "updateConfig"
